theme: jekyll-theme-minimal
title: grischka's homepage
description: Bookmark this to keep an eye on my project updates!
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
